/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.ap220191.ec02_controle_tarefas.model;

import br.com.ap220191.ec02_controle_tarefas.util.Consulta;
import br.com.ap220191.ec02_controle_tarefas.util.Perfil;
import br.com.ap220191.ec02_controle_tarefas.util.Projeto;
import br.com.ap220191.ec02_controle_tarefas.util.Tarefa;
import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Diego dos Santos
 */
public class Sistema extends javax.swing.JFrame {
    
    private int ii=0;
    
    private ArrayList<Perfil> perfis = new ArrayList<>();
    private ArrayList<Tarefa> tarefas = new ArrayList<>();
    private ArrayList<Projeto> projetos = new ArrayList<>();
    
    /**
     * Creates new form Sistema
     */
    public Sistema() {
        
        initComponents();
        
        this.jcbTIPOPerfil.removeAllItems();
        
        this.jcbTIPOPerfil.addItem("SELECIONE");
        this.jcbTIPOPerfil.addItem("Administrador");
        this.jcbTIPOPerfil.addItem("Usuário");
        
        this.jcbTIPO.addItem("SELECIONE");
        this.jcbTIPO.addItem("DEFEITO");
        this.jcbTIPO.addItem("MELHORIA");
        
        this.jcbPROJETOconsulta.addItem("SELECIONE");
        
        this.jcbFASEconsulta.addItem("SELECIONE");
        this.jcbFASEconsulta.addItem("Criado");
        this.jcbFASEconsulta.addItem("Iniciado");
        this.jcbFASEconsulta.addItem("Etapa 1");
        this.jcbFASEconsulta.addItem("Etapa 2");
        this.jcbFASEconsulta.addItem("Etapa 3");
        this.jcbFASEconsulta.addItem("Etapa 4");
        this.jcbFASEconsulta.addItem("Etapa 5");
        this.jcbFASEconsulta.addItem("Finalizado");
        
        this.jcbFASE.addItem("SELECIONE");
        this.jcbFASE.addItem("Etapa 1");
        this.jcbFASE.addItem("Etapa 2");
        this.jcbFASE.addItem("Etapa 3");
        this.jcbFASE.addItem("Etapa 4");
        this.jcbFASE.addItem("Etapa 5");
        this.jcbFASE.addItem("Finalizado");
        
        this.jcbESTADOconsulta.addItem("SELECIONE");
        this.jcbESTADOconsulta.addItem("Cadastrada");
        this.jcbESTADOconsulta.addItem("Em andamento");
        this.jcbESTADOconsulta.addItem("Concluída");
        this.jcbESTADOconsulta.addItem("Descartada");
        
        this.jcbTIPOconsulta.addItem("SELECIONE");
        this.jcbTIPOconsulta.addItem("DEFEITO");
        this.jcbTIPOconsulta.addItem("MELHORIA");
        
        this.jcbRELATORconsulta.addItem("SELECIONE");
        this.jcbEXECUTORconsulta.addItem("SELECIONE");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNOME = new javax.swing.JTextField();
        txtCARGO = new javax.swing.JTextField();
        txtSETOR = new javax.swing.JTextField();
        criaPERFIL = new javax.swing.JButton();
        jcbTIPOPerfil = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaPERFIL = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jcbTIPO = new javax.swing.JComboBox<>();
        txtNOMEtarefa = new javax.swing.JTextField();
        txtDESCRICAO = new javax.swing.JTextField();
        cadastraTAREFA = new javax.swing.JButton();
        jcbRELATOR = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jcbTarefaparaINICIAR = new javax.swing.JComboBox<>();
        txtPrazoTAREFA = new javax.swing.JTextField();
        iniciaTAREFA = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jcbTarefaparaCONCLUIR = new javax.swing.JComboBox<>();
        concluiTAREFA = new javax.swing.JButton();
        txtTarefaSOLUCAO = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jcbTarefaparaDESCARTAR = new javax.swing.JComboBox<>();
        descartarTAREFA = new javax.swing.JButton();
        jLabel33 = new javax.swing.JLabel();
        jcbUSUARIOiniciar = new javax.swing.JComboBox<>();
        jcbUSUARIOconcluir = new javax.swing.JComboBox<>();
        jcbUSUARIOdescatar = new javax.swing.JComboBox<>();
        jLabel34 = new javax.swing.JLabel();
        txtINICIOtarefa = new javax.swing.JFormattedTextField();
        txtTAREFAconclusao = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        projetoNOME = new javax.swing.JTextField();
        criaPROJETO = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jcbTAREFASprojeto = new javax.swing.JComboBox<>();
        jcbPROJETOSadicionarTAREFAS = new javax.swing.JComboBox<>();
        ADICIONARtarefaPROJETO = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jcbPROJETOSiniciar = new javax.swing.JComboBox<>();
        iniciaPROJETO = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        txtPRAZOprojeto = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jcbPROJETOSconcluir = new javax.swing.JComboBox<>();
        concluiPROJETO = new javax.swing.JButton();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        alteraFASE = new javax.swing.JButton();
        jcbPROJETOfase = new javax.swing.JComboBox<>();
        jcbFASE = new javax.swing.JComboBox<>();
        txtPROJETOinicio = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        txtPROJETOconclusao = new javax.swing.JFormattedTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jcbPROJETOconsulta = new javax.swing.JComboBox<>();
        jcbFASEconsulta = new javax.swing.JComboBox<>();
        jcbTIPOconsulta = new javax.swing.JComboBox<>();
        jcbESTADOconsulta = new javax.swing.JComboBox<>();
        jcbRELATORconsulta = new javax.swing.JComboBox<>();
        jcbEXECUTORconsulta = new javax.swing.JComboBox<>();
        jLabel44 = new javax.swing.JLabel();
        jcbUSUARIOconsulta = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SISTEMA DE CONTROLE DE TAREFAS");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "USUÁRIOS", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel1.setPreferredSize(new java.awt.Dimension(160, 250));

        jLabel2.setText("Nome:");

        jLabel3.setText("Perfil:");

        jLabel4.setText("Cargo:");

        jLabel5.setText("Setor:");

        txtNOME.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNOME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNOMEActionPerformed(evt);
            }
        });

        txtCARGO.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtSETOR.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        criaPERFIL.setText("ADICIONAR");
        criaPERFIL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                criaPERFILActionPerformed(evt);
            }
        });

        tabelaPERFIL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "       Usuário", "         Perfil", "        Cargo", "        Setor  "
            }
        ));
        jScrollPane1.setViewportView(tabelaPERFIL);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNOME)
                            .addComponent(txtCARGO)
                            .addComponent(jcbTIPOPerfil, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(criaPERFIL)
                                .addGap(0, 27, Short.MAX_VALUE))
                            .addComponent(txtSETOR))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtNOME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jcbTIPOPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtCARGO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtSETOR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addComponent(criaPERFIL)
                        .addGap(17, 17, 17))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "TAREFAS", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jLabel7.setText("RELATOR:");

        jLabel9.setText("NOME:");

        jLabel10.setText("TIPO:");

        jLabel11.setText("DESCRIÇÃO:");

        jcbTIPO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbTIPOActionPerformed(evt);
            }
        });

        txtNOMEtarefa.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNOMEtarefa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNOMEtarefaActionPerformed(evt);
            }
        });

        cadastraTAREFA.setText("CADASTRAR");
        cadastraTAREFA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastraTAREFAActionPerformed(evt);
            }
        });

        jLabel12.setText("TAREFA:");

        jLabel14.setText("INÍCIO:");

        jLabel15.setText("PRAZO:");

        txtPrazoTAREFA.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPrazoTAREFA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrazoTAREFAActionPerformed(evt);
            }
        });

        iniciaTAREFA.setText("INICIAR");
        iniciaTAREFA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciaTAREFAActionPerformed(evt);
            }
        });

        jLabel13.setText("TAREFA:");

        jcbTarefaparaCONCLUIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbTarefaparaCONCLUIRActionPerformed(evt);
            }
        });

        concluiTAREFA.setText("CONCLUIR");
        concluiTAREFA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                concluiTAREFAActionPerformed(evt);
            }
        });

        txtTarefaSOLUCAO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTarefaSOLUCAOActionPerformed(evt);
            }
        });

        jLabel16.setText("SOLUÇÃO:");

        jLabel17.setText("TAREFA:");

        jLabel18.setText("DESCARTAR");

        jLabel19.setText("CONCLUIR");

        jLabel20.setText("INICIAR");

        jLabel21.setText("CADASTRAR");

        descartarTAREFA.setText("DESCARTAR");
        descartarTAREFA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descartarTAREFAActionPerformed(evt);
            }
        });

        jLabel33.setText("EXECUTOR:");

        jLabel34.setText("USUÁRIO:");

        try {
            txtINICIOtarefa.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtINICIOtarefa.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        try {
            txtTAREFAconclusao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtTAREFAconclusao.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel1.setText("Data:");

        jLabel22.setText("EXECUTOR:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel20)
                        .addGap(137, 137, 137)
                        .addComponent(jLabel19)
                        .addGap(127, 127, 127))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDESCRICAO, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(25, 25, 25)
                                        .addComponent(cadastraTAREFA))
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addContainerGap()
                                            .addComponent(jLabel9)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtNOMEtarefa, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jcbRELATOR, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel10)
                                        .addGap(29, 29, 29)
                                        .addComponent(jcbTIPO, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(22, 22, 22)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addGap(100, 100, 100)
                                            .addComponent(txtPrazoTAREFA, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                            .addComponent(iniciaTAREFA, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(32, 32, 32))
                                        .addComponent(txtINICIOtarefa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel22)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jLabel12)
                                                        .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING))
                                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                                        .addGap(9, 9, 9)
                                                        .addComponent(jLabel15)))
                                                .addGap(10, 10, 10)))
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jcbTarefaparaINICIAR, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jcbUSUARIOiniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(jLabel11)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel33)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jcbTarefaparaCONCLUIR, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jcbUSUARIOconcluir, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel34))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(47, 47, 47)
                                        .addComponent(concluiTAREFA, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(jLabel1)
                                                .addGap(5, 5, 5)
                                                .addComponent(jLabel16))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel13)
                                                .addGap(169, 169, 169)
                                                .addComponent(jLabel17))))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtTAREFAconclusao, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtTarefaSOLUCAO, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(68, 68, 68))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(descartarTAREFA)
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jcbUSUARIOdescatar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jcbTarefaparaDESCARTAR, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(0, 0, Short.MAX_VALUE)))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21)
                    .addComponent(jLabel18))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jcbUSUARIOconcluir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel34)
                            .addComponent(jcbUSUARIOdescatar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jcbTarefaparaDESCARTAR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTAREFAconclusao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(jLabel11)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jcbUSUARIOiniciar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel33)
                            .addComponent(jLabel22)
                            .addComponent(jcbRELATOR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel12)
                                .addComponent(txtNOMEtarefa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel9))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jcbTarefaparaINICIAR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel13)
                                .addComponent(jcbTarefaparaCONCLUIR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtINICIOtarefa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jcbTIPO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel10))
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPrazoTAREFA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtTarefaSOLUCAO, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(62, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtDESCRICAO)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cadastraTAREFA)
                            .addComponent(iniciaTAREFA)
                            .addComponent(descartarTAREFA)
                            .addComponent(concluiTAREFA))
                        .addGap(18, 18, 18))))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "PROJETOS", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jLabel23.setText("NOVO PROJETO");

        jLabel24.setText("Nome:");

        projetoNOME.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        criaPROJETO.setText("CRIAR");
        criaPROJETO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                criaPROJETOActionPerformed(evt);
            }
        });

        jLabel25.setText("ADICIONAR TAREFAS");

        jLabel26.setText("Tarefa:");

        jLabel27.setText("Projeto:");

        jcbTAREFASprojeto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbTAREFASprojetoActionPerformed(evt);
            }
        });

        ADICIONARtarefaPROJETO.setText("ADICIONAR");
        ADICIONARtarefaPROJETO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADICIONARtarefaPROJETOActionPerformed(evt);
            }
        });

        jLabel28.setText("INICIAR PROJETO");

        jLabel29.setText("Projeto:");

        iniciaPROJETO.setText("INICIAR");
        iniciaPROJETO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciaPROJETOActionPerformed(evt);
            }
        });

        jLabel30.setText("Início:");

        jLabel31.setText("Prazo:");

        txtPRAZOprojeto.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel35.setText("CONCLUIR PROJETO");

        jLabel36.setText("Projeto:");

        jcbPROJETOSconcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbPROJETOSconcluirActionPerformed(evt);
            }
        });

        concluiPROJETO.setText("CONCLUIR");
        concluiPROJETO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                concluiPROJETOActionPerformed(evt);
            }
        });

        jLabel45.setText("ALTERA FASE");

        jLabel46.setText("Fase:");

        jLabel47.setText("Projeto:");

        alteraFASE.setText("ALTERAR");
        alteraFASE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alteraFASEActionPerformed(evt);
            }
        });

        jcbPROJETOfase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbPROJETOfaseActionPerformed(evt);
            }
        });

        jcbFASE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbFASEActionPerformed(evt);
            }
        });

        try {
            txtPROJETOinicio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtPROJETOinicio.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel6.setText("Data:");

        try {
            txtPROJETOconclusao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtPROJETOconclusao.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(jLabel25)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                        .addGap(48, 48, 48)
                                        .addComponent(jLabel24)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel23)
                                            .addComponent(projetoNOME, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(32, 32, 32)))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel27)
                                        .addGap(2, 2, 2)
                                        .addComponent(jcbPROJETOSadicionarTAREFAS, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel26)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jcbTAREFASprojeto, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(criaPROJETO)
                                .addGap(77, 77, 77)
                                .addComponent(ADICIONARtarefaPROJETO)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel31)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel29)
                                    .addComponent(jLabel30))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel28)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel45)
                                        .addGap(40, 40, 40))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jcbPROJETOSiniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtPRAZOprojeto, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtPROJETOinicio, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGap(27, 27, 27)
                                                .addComponent(jLabel47))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel46)))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jcbPROJETOfase, 0, 129, Short.MAX_VALUE)
                                            .addComponent(jcbFASE, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(iniciaPROJETO)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(alteraFASE)
                                .addGap(33, 33, 33)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel36)
                                .addGap(1, 1, 1))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(8, 8, 8)))))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                            .addComponent(concluiPROJETO)
                            .addGap(19, 19, 19))
                        .addComponent(jLabel35, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(jcbPROJETOSconcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(txtPROJETOconclusao, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel25)
                                .addComponent(jLabel28)
                                .addComponent(jLabel45))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel35)))
                .addGap(37, 37, 37)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel26)
                                        .addComponent(jcbTAREFASprojeto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jcbPROJETOSconcluir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel36))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtPROJETOconclusao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel6))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ADICIONARtarefaPROJETO)
                                    .addComponent(iniciaPROJETO)
                                    .addComponent(concluiPROJETO)
                                    .addComponent(alteraFASE)
                                    .addComponent(criaPROJETO)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel29)
                                            .addComponent(jcbPROJETOSiniciar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel30)
                                                .addComponent(jcbPROJETOSadicionarTAREFAS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel27))
                                            .addComponent(txtPROJETOinicio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel31)
                                            .addComponent(txtPRAZOprojeto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(13, 13, 13))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel24)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(projetoNOME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(21, 21, 21))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jcbFASE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel46)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel47)
                                .addComponent(jcbPROJETOfase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "CONSULTAS", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jLabel38.setText("Por Projeto:");

        jLabel39.setText("Por Fase de Projeto:");

        jLabel40.setText("Por Tipo de Tarefa:");

        jLabel41.setText("Por Estado da Tarefa:");

        jLabel42.setText("Por Relator:");

        jLabel43.setText("Por Executor:");

        jcbPROJETOconsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbPROJETOconsultaActionPerformed(evt);
            }
        });

        jcbFASEconsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbFASEconsultaActionPerformed(evt);
            }
        });

        jcbTIPOconsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbTIPOconsultaActionPerformed(evt);
            }
        });

        jcbESTADOconsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbESTADOconsultaActionPerformed(evt);
            }
        });

        jcbRELATORconsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbRELATORconsultaActionPerformed(evt);
            }
        });

        jcbEXECUTORconsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbEXECUTORconsultaActionPerformed(evt);
            }
        });

        jLabel44.setText("Usuário:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(jLabel44)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcbUSUARIOconsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel38)
                        .addGap(70, 70, 70))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel42)
                            .addComponent(jLabel41, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel40)
                            .addComponent(jLabel39, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jcbRELATORconsulta, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jcbFASEconsulta, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jcbPROJETOconsulta, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jcbTIPOconsulta, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jcbESTADOconsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbEXECUTORconsulta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38)
                    .addComponent(jcbPROJETOconsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbFASEconsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel39))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel44)
                        .addComponent(jcbUSUARIOconsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jcbTIPOconsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel40)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbESTADOconsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel41))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbRELATORconsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel42))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcbEXECUTORconsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel43))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 666, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void criaPERFILActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criaPERFILActionPerformed
        
        if(this.jcbTIPOPerfil.getSelectedItem().toString()=="Administrador"||this.jcbTIPOPerfil.getSelectedItem().toString()=="Usuário")
        {
            //Cria perfil para ser adicionado na lista do sistema
            Perfil perfil = new Perfil();
            perfil.Perfil(txtNOME.getText(), txtCARGO.getText(), this.jcbTIPOPerfil.getSelectedItem().toString(), txtSETOR.getText());

            //Cria uma lista de perfis gerados no sistema
            perfis.add(perfil);
        
            //Crias as DASHBoard do RELATOR e do EXECUTOR para criação da tarefa        
            this.jcbRELATOR.addItem(perfil.getNomeUsuario());
               
            this.jcbUSUARIOiniciar.addItem(perfil.getNomeUsuario());
            this.jcbUSUARIOconcluir.addItem(perfil.getNomeUsuario());
            this.jcbUSUARIOdescatar.addItem(perfil.getNomeUsuario());
        
            this.jcbUSUARIOconsulta.addItem(perfil.getNomeUsuario());
            this.jcbRELATORconsulta.addItem(perfil.getNomeUsuario());
            this.jcbEXECUTORconsulta.addItem(perfil.getNomeUsuario());
       
            //Envia dados para a tabela 
            DefaultTableModel dtmPERFIL = (DefaultTableModel) tabelaPERFIL.getModel();
            Object [] dados  = {perfis.get(ii).getNomeUsuario(), perfis.get(ii).getTipoPerfil(), perfis.get(ii).getCargo(),perfis.get(ii).getSetorTrabalho()};
            dtmPERFIL.addRow(dados);
        
            ii++;
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Perfil inválido!");
        }
    }//GEN-LAST:event_criaPERFILActionPerformed
    
    private void txtNOMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNOMEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNOMEActionPerformed

    private void txtTarefaSOLUCAOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTarefaSOLUCAOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTarefaSOLUCAOActionPerformed

    private void concluiTAREFAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_concluiTAREFAActionPerformed
        try 
        {
            //Entrada de dados para data de CONCLUSAO da tarefa.
            String dataCONCLUSAO = txtTAREFAconclusao.getText();
            String[] dataSEPARADA = dataCONCLUSAO.split("/");
            LocalDate conclusao = LocalDate.of(Integer.parseInt(dataSEPARADA[2]), Integer.parseInt(dataSEPARADA[1]), Integer.parseInt(dataSEPARADA[0])); 

            for(int j=0;j<perfis.size();j++)
            {
                //Verifica o usuário informado
                if(perfis.get(j).getNomeUsuario()==this.jcbUSUARIOconcluir.getSelectedItem().toString())
                {
                    for(int i=0;i<tarefas.size();i++)
                    {
                        //Verifica a tarefa selecionada
                        if(tarefas.get(i).getTarefaNome()==this.jcbTarefaparaCONCLUIR.getSelectedItem().toString())
                        {
                            //Entra do com os dados na tarefa
                            tarefas.get(i).concluirTarefa(perfis.get(j),txtTarefaSOLUCAO.getText(), conclusao, true); //selecionar dados no txt de inicio e converter para date
                        }
                    }
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Informe os dados corretamente!");
        }
        
    }//GEN-LAST:event_concluiTAREFAActionPerformed

    private void jcbTarefaparaCONCLUIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbTarefaparaCONCLUIRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbTarefaparaCONCLUIRActionPerformed

    private void iniciaTAREFAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciaTAREFAActionPerformed

        try 
        {
            int prazo = Integer.parseInt(txtPrazoTAREFA.getText());
        
            String inicioTAREFA = this.txtINICIOtarefa.getText();
            String[] dataSEPARADA = inicioTAREFA.split("/");
            LocalDate inicio = LocalDate.of(Integer.parseInt(dataSEPARADA[2]), Integer.parseInt(dataSEPARADA[1]), Integer.parseInt(dataSEPARADA[0]));
        
            for(int j=0;j<perfis.size();j++)
            {
                //Faz varredura nos perfis CADASTRADOS no sistema
                if(perfis.get(j).getNomeUsuario()==this.jcbUSUARIOiniciar.getSelectedItem().toString())
                {
                    for(int i=0;i<tarefas.size();i++)
                    {
                        //Faz varredura nas tarefas CADASTRADAS no sistema
                        if(tarefas.get(i).getTarefaNome()==this.jcbTarefaparaINICIAR.getSelectedItem())
                        {
                            if(tarefas.get(i).getEstado()=="Cadastrada")
                            {
                                //Verifica se a tarefa é uma prioridade (DEFEITO)
                                if(tarefas.get(i).isPrioridade())
                                {
                                    //Se SIM (DEFEITO), inicia a tarefa, caso o perfil seja aceito
                                    tarefas.get(i).iniciarTarefa(perfis.get(j),inicio, prazo);

                                    //Se a tarefa foi iniciada, ira por emAndamento em true e irá permitir que getEstado informe "Em andamento"
                                    if(tarefas.get(i).getEstado()=="Em andamento")
                                    {
                                        this.jcbTarefaparaCONCLUIR.addItem(tarefas.get(i).getTarefaNome());
                                        this.jcbTarefaparaDESCARTAR.addItem(tarefas.get(i).getTarefaNome());
                                    }
                                }
                                else
                                {
                                    int count=0;
                                    //Se não, varre as tarefas para verificar as tarefas de DEFEITO que ainda não foram iniciadas ou iniciadas
                                    for(int k=0;k<tarefas.size();k++)
                                    {
                                        //Se estiverem em andamento não permite que uma tarefa MELHORIA seja iniciada
                                        if(tarefas.get(k).isPrioridade()&&tarefas.get(k).isEmAndamento())
                                        {
                                            count++;
                                        }
                                    }

                                    if(count==0)
                                    {
                                        //Inicia a tarefa, caso o perfil esteja correto
                                        tarefas.get(i).iniciarTarefa(perfis.get(j),inicio, prazo);

                                        if(tarefas.get(i).getEstado()=="Em andamento")
                                        {//Caso as tarefas de DEFEITO tenham sido finalizadas, inicia a tarefa com melhoria.
                                            this.jcbTarefaparaCONCLUIR.addItem(tarefas.get(i).getTarefaNome());
                                            this.jcbTarefaparaDESCARTAR.addItem(tarefas.get(i).getTarefaNome());
                                        }
                                    } else
                                    {
                                        JOptionPane.showMessageDialog(null, "Tarefas com prioridade ainda em andamento");
                                    }
                                }
                            } else
                            {
                                JOptionPane.showMessageDialog(null, "Tarefa já foi iniciada!");
                            }
                        }
                    }
                }
            }
        
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Entre com os dados corretamente!");
        }
        
        
        
    }//GEN-LAST:event_iniciaTAREFAActionPerformed

    private void cadastraTAREFAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastraTAREFAActionPerformed
        
        Perfil p = new Perfil();

        Tarefa tarefa = new Tarefa();
        
        for(int i=0;i<perfis.size();i++)
        {
            if(perfis.get(i).getNomeUsuario()==this.jcbRELATOR.getSelectedItem().toString())
            {
                    p = perfis.get(i);
                
                    //Cria o objeto TAREFA
                    tarefa.cadastrarTarefa(p, txtNOMEtarefa.getText(),jcbTIPO.getSelectedItem().toString());
                    
                    tarefa.descreverTarefa(p, txtDESCRICAO.getText());
                    
                    if(tarefa.getEstado()=="Cadastrada")
                    {
                        //Cria a lista de tarefas do sistema
                        tarefas.add(tarefa);

                        //Cria a DASHboard de tarefas a serem INICIADAS
                        this.jcbTarefaparaINICIAR.addItem(tarefa.getTarefaNome());

                        //Cria a DASHBOARD de tarefas a serem ADICIONADAS a Projetos
                        this.jcbTAREFASprojeto.addItem(tarefa.getTarefaNome());
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(null,"Informe os dados corretamente!");
                    }
            }
        }
    }//GEN-LAST:event_cadastraTAREFAActionPerformed

    private void txtNOMEtarefaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNOMEtarefaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNOMEtarefaActionPerformed

    private void descartarTAREFAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descartarTAREFAActionPerformed
        
        for(int j=0;j<perfis.size(); j++)
        {
            //Puxa o usuário selecionado
            if(perfis.get(j).getNomeUsuario()==this.jcbUSUARIOdescatar.getSelectedItem().toString())
            {
                for(int i=0;i<tarefas.size();i++)
                {
                    //Puxa a tarefa selecionada
                    if(tarefas.get(i).getTarefaNome()==this.jcbTarefaparaDESCARTAR.getSelectedItem().toString())
                    {
                        //Modifica o estado da tarefa
                        tarefas.get(i).descartarTarefa(perfis.get(j),true);
                    }
                }
            }
        }
    }//GEN-LAST:event_descartarTAREFAActionPerformed

    private void criaPROJETOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criaPROJETOActionPerformed
        //this.jcbPROJETOSconsulta.enable();
        
        Projeto projeto = new Projeto();
        
        projeto.criarProjeto(projetoNOME.getText());
        
        this.jcbPROJETOSadicionarTAREFAS.addItem(projeto.getProjNome());
        
        this.jcbPROJETOSiniciar.addItem(projeto.getProjNome());
        
        this.jcbPROJETOSconcluir.addItem(projeto.getProjNome());
        
        this.jcbPROJETOfase.addItem(projeto.getProjNome());
        
        this.jcbPROJETOconsulta.addItem(projeto.getProjNome());
        
        projetos.add(projeto);
        
    }//GEN-LAST:event_criaPROJETOActionPerformed

    private void jcbTAREFASprojetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbTAREFASprojetoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbTAREFASprojetoActionPerformed

    private void ADICIONARtarefaPROJETOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADICIONARtarefaPROJETOActionPerformed
        
        for(int i=0;i<projetos.size();i++)
        {
            if(String.valueOf(this.jcbPROJETOSadicionarTAREFAS.getSelectedItem())==projetos.get(i).getProjNome())
            {
                for(int j=0;j<tarefas.size();j++)
                {
                    if(String.valueOf(this.jcbTAREFASprojeto.getSelectedItem())==tarefas.get(j).getTarefaNome())
                    {
                        //Vincula o PROJETO criado à TAREFA
                        tarefas.get(j).setProjetoVinculado(projetos.get(i));
                    }
                }
            }
        }
    }//GEN-LAST:event_ADICIONARtarefaPROJETOActionPerformed

    private void iniciaPROJETOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciaPROJETOActionPerformed
        
        try
        {
            int prazo = Integer.parseInt(txtPRAZOprojeto.getText());
        
            //Entrada de dados para a data de INICIO do projeto
            String inicioPROJETO = this.txtPROJETOinicio.getText();
            String[] dataSEPARADA = inicioPROJETO.split("/");
            LocalDate inicio = LocalDate.of(Integer.parseInt(dataSEPARADA[2]), Integer.parseInt(dataSEPARADA[1]), Integer.parseInt(dataSEPARADA[0]));

            for(int i=0;i<projetos.size();i++)
            {
                //Puxa o projeto selecionado
                if(projetos.get(i).getProjNome()==this.jcbPROJETOSadicionarTAREFAS.getSelectedItem().toString())
                {
                    //Atribui dados de INICIO e PRAZO ao projeto
                    projetos.get(i).iniciarProjeto(inicio, prazo);

                    for (int k=0;k<tarefas.size();k++)
                    {
                        //Puxa tarefa que tem esse projeto
                        if(tarefas.get(k).getProjetoVinculado().getProjNome().equals(projetos.get(i).getProjNome()))
                                {
                                    //Atualiza a tarefa  com projeto iniciado
                                    tarefas.get(k).setProjetoVinculado(projetos.get(i));
                                }
                    }
                }
            }
        } catch (Exception e)
        {
            JOptionPane.showMessageDialog(null,"Informe os dados corretamente!");
        }
        
    }//GEN-LAST:event_iniciaPROJETOActionPerformed

    private void concluiPROJETOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_concluiPROJETOActionPerformed
        
        try
        {
            //Entrada de dados para data de CONCLUSAO 
            String concluirPROJETO = this.txtPROJETOconclusao.getText();
            String[] dataSEPARADA = concluirPROJETO.split("/");
            LocalDate conclusao = LocalDate.of(Integer.parseInt(dataSEPARADA[2]), Integer.parseInt(dataSEPARADA[1]), Integer.parseInt(dataSEPARADA[0])); 

            for(int i=0;i<projetos.size();i++)
            {
                //Puxa o projeto selecionado
                if(this.jcbPROJETOSconcluir.getSelectedItem().toString()==projetos.get(i).getProjNome())
                {
                    for(int j=0;j<tarefas.size();j++)
                    {
                        //Puxa tarefa selecionada
                        if(tarefas.get(j).getProjetoVinculado().getProjNome()==this.jcbPROJETOSconcluir.getSelectedItem().toString())
                        {
                            //Atualiza projeto puxado
                            projetos.get(i).concluirProjeto(conclusao,true);

                            //Atualiza tarefa puxada
                            tarefas.get(j).setProjetoVinculado(projetos.get(i));
                        }
                    }
                }
            }
        } catch (Exception e)
        {
            JOptionPane.showMessageDialog(null,"Informe os dados corretamente!");
        }
        
    }//GEN-LAST:event_concluiPROJETOActionPerformed

    private void jcbTIPOconsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbTIPOconsultaActionPerformed
        Consulta cons = new Consulta();
        try
        {
            for(int i=0; i<perfis.size();i++)
            {
                if(perfis.get(i).getNomeUsuario()==this.jcbUSUARIOconsulta.getSelectedItem().toString())
                {
                    cons.porTipoDeTAREFA(perfis.get(i),this.jcbTIPOconsulta.getSelectedItem().toString(), tarefas);
                }
            }
        } catch (Exception e) 
        {
            JOptionPane.showMessageDialog(null,"Erro: "+e);
        }
        
    }//GEN-LAST:event_jcbTIPOconsultaActionPerformed

    private void jcbPROJETOconsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbPROJETOconsultaActionPerformed
        
        Consulta cons = new Consulta();
            
        for(int i=0; i<perfis.size();i++)
        {
            if(perfis.get(i).getNomeUsuario()==String.valueOf(this.jcbUSUARIOconsulta.getSelectedItem()))
            {
                cons.porPROJETO(perfis.get(i),String.valueOf(this.jcbPROJETOconsulta.getSelectedItem()), tarefas);
            }
        }
        
    }//GEN-LAST:event_jcbPROJETOconsultaActionPerformed

    private void jcbFASEconsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbFASEconsultaActionPerformed
        
        Consulta cons = new Consulta();
        
        for(int i=0; i<perfis.size();i++)
        {
            if(perfis.get(i).getNomeUsuario()==this.jcbUSUARIOconsulta.getSelectedItem().toString())
            {
                cons.porFASE(perfis.get(i),this.jcbFASEconsulta.getSelectedItem().toString(), tarefas);
            }
        }
        
    }//GEN-LAST:event_jcbFASEconsultaActionPerformed

    private void jcbTIPOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbTIPOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbTIPOActionPerformed

    private void jcbPROJETOSconcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbPROJETOSconcluirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbPROJETOSconcluirActionPerformed

    private void jcbPROJETOfaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbPROJETOfaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbPROJETOfaseActionPerformed

    private void jcbFASEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbFASEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbFASEActionPerformed

    private void alteraFASEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alteraFASEActionPerformed
        
        for(int i=0;i<projetos.size();i++)
        {
            if(projetos.get(i).getProjNome()==String.valueOf(this.jcbPROJETOfase.getSelectedItem())&&this.jcbFASE.getSelectedItem().toString()!="SELECIONE")
            {
                projetos.get(i).setProjFase(String.valueOf(this.jcbFASE.getSelectedItem()));

                for(int j=0;j<tarefas.size();j++)
                {
                    try
                    {
                        if(tarefas.get(j).getProjetoVinculado().getProjNome()==projetos.get(i).getProjNome())
                        {
                            tarefas.get(j).setProjetoVinculado(projetos.get(i));
                        }
                    } catch (Exception e) 
                    {
                        
                    }
                    
                }
            }
        }
    }//GEN-LAST:event_alteraFASEActionPerformed

    private void txtPrazoTAREFAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrazoTAREFAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrazoTAREFAActionPerformed

    private void jcbRELATORconsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbRELATORconsultaActionPerformed
        Consulta cons = new Consulta();
        
        for(int i=0; i<perfis.size();i++)
        {
            if(perfis.get(i).getNomeUsuario()==this.jcbUSUARIOconsulta.getSelectedItem().toString())
            {
                cons.porRELATOR(perfis.get(i),this.jcbRELATORconsulta.getSelectedItem().toString(), tarefas);
            }
        }
    }//GEN-LAST:event_jcbRELATORconsultaActionPerformed

    private void jcbEXECUTORconsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbEXECUTORconsultaActionPerformed
        Consulta cons = new Consulta();
        
       
        for(int i=0; i<perfis.size();i++)
        {
            if(perfis.get(i).getNomeUsuario()==this.jcbUSUARIOconsulta.getSelectedItem().toString())
            {
                cons.porEXECUTOR(perfis.get(i),this.jcbEXECUTORconsulta.getSelectedItem().toString(), tarefas);
            }
        }
    }//GEN-LAST:event_jcbEXECUTORconsultaActionPerformed

    private void jcbESTADOconsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbESTADOconsultaActionPerformed
        Consulta cons = new Consulta();
        
        for(int i=0; i<perfis.size();i++)
        {
            if(perfis.get(i).getNomeUsuario()==String.valueOf(this.jcbUSUARIOconsulta.getSelectedItem()))
            {
                cons.porEstadoTAREFA(perfis.get(i),String.valueOf(this.jcbESTADOconsulta.getSelectedItem()), tarefas);
            }
        }
    }//GEN-LAST:event_jcbESTADOconsultaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sistema().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ADICIONARtarefaPROJETO;
    private javax.swing.JButton alteraFASE;
    private javax.swing.JButton cadastraTAREFA;
    private javax.swing.JButton concluiPROJETO;
    private javax.swing.JButton concluiTAREFA;
    private javax.swing.JButton criaPERFIL;
    private javax.swing.JButton criaPROJETO;
    private javax.swing.JButton descartarTAREFA;
    private javax.swing.JButton iniciaPROJETO;
    private javax.swing.JButton iniciaTAREFA;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jcbESTADOconsulta;
    private javax.swing.JComboBox<String> jcbEXECUTORconsulta;
    private javax.swing.JComboBox<String> jcbFASE;
    private javax.swing.JComboBox<String> jcbFASEconsulta;
    private javax.swing.JComboBox<String> jcbPROJETOSadicionarTAREFAS;
    private javax.swing.JComboBox<String> jcbPROJETOSconcluir;
    private javax.swing.JComboBox<String> jcbPROJETOSiniciar;
    private javax.swing.JComboBox<String> jcbPROJETOconsulta;
    private javax.swing.JComboBox<String> jcbPROJETOfase;
    private javax.swing.JComboBox<String> jcbRELATOR;
    private javax.swing.JComboBox<String> jcbRELATORconsulta;
    private javax.swing.JComboBox<String> jcbTAREFASprojeto;
    private javax.swing.JComboBox<String> jcbTIPO;
    private javax.swing.JComboBox<String> jcbTIPOPerfil;
    private javax.swing.JComboBox<String> jcbTIPOconsulta;
    private javax.swing.JComboBox<String> jcbTarefaparaCONCLUIR;
    private javax.swing.JComboBox<String> jcbTarefaparaDESCARTAR;
    private javax.swing.JComboBox<String> jcbTarefaparaINICIAR;
    private javax.swing.JComboBox<String> jcbUSUARIOconcluir;
    private javax.swing.JComboBox<String> jcbUSUARIOconsulta;
    private javax.swing.JComboBox<String> jcbUSUARIOdescatar;
    private javax.swing.JComboBox<String> jcbUSUARIOiniciar;
    private javax.swing.JTextField projetoNOME;
    private javax.swing.JTable tabelaPERFIL;
    private javax.swing.JTextField txtCARGO;
    private javax.swing.JTextField txtDESCRICAO;
    private javax.swing.JFormattedTextField txtINICIOtarefa;
    private javax.swing.JTextField txtNOME;
    private javax.swing.JTextField txtNOMEtarefa;
    private javax.swing.JTextField txtPRAZOprojeto;
    private javax.swing.JFormattedTextField txtPROJETOconclusao;
    private javax.swing.JFormattedTextField txtPROJETOinicio;
    private javax.swing.JTextField txtPrazoTAREFA;
    private javax.swing.JTextField txtSETOR;
    private javax.swing.JFormattedTextField txtTAREFAconclusao;
    private javax.swing.JTextField txtTarefaSOLUCAO;
    // End of variables declaration//GEN-END:variables
}
