/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.ap220191.ec02_controle_tarefas.model;

import br.com.ap220191.ec02_controle_tarefas.util.Consulta;
import br.com.ap220191.ec02_controle_tarefas.util.Perfil;
import br.com.ap220191.ec02_controle_tarefas.util.Projeto;
import br.com.ap220191.ec02_controle_tarefas.util.Tarefa;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Diego dos Santos
 */
public class Sistema extends javax.swing.JFrame {
    //private Perfil perfil;
    //private Tarefa tarefa;
    private Projeto projeto;
   //private ;
    private int ii=0;
    
    private ArrayList<Perfil> perfis = new ArrayList<>();
    private ArrayList<Tarefa> tarefas = new ArrayList<>();
    private ArrayList<Projeto> projetos = new ArrayList<>();
    
    public ArrayList<Tarefa> getTAREFASlista()
    {
        return tarefas;
    }
    /**
     * Creates new form Sistema
     */
    public Sistema() {
        initComponents();
        
        this.jcbTIPOPerfil.removeAllItems();
        
        this.jcbTIPOPerfil.addItem("Administrador");
        this.jcbTIPOPerfil.addItem("Usuário");
        
        this.jcbTIPO.addItem("MELHORIA");
        this.jcbTIPO.addItem("DEFEITO");
        
        this.jcbPROJETOconsulta.addItem("S/A");
        
        this.jcbFASEconsulta.addItem("S/A");
        this.jcbFASEconsulta.addItem("Criado");
        this.jcbFASEconsulta.addItem("Iniciado");
        this.jcbFASEconsulta.addItem("Etapa 1");
        this.jcbFASEconsulta.addItem("Etapa 2");
        this.jcbFASEconsulta.addItem("Etapa 3");
        this.jcbFASEconsulta.addItem("Etapa 4");
        this.jcbFASEconsulta.addItem("Etapa 5");
        this.jcbFASEconsulta.addItem("Finalizado");
        
        this.jcbFASE.addItem("Etapa 1");
        this.jcbFASE.addItem("Etapa 2");
        this.jcbFASE.addItem("Etapa 3");
        this.jcbFASE.addItem("Etapa 4");
        this.jcbFASE.addItem("Etapa 5");
        this.jcbFASE.addItem("Finalizado");
        
        this.jcbESTADOconsulta.addItem("S/A");
        this.jcbESTADOconsulta.addItem("Cadastrada");
        this.jcbESTADOconsulta.addItem("Iniciada");
        this.jcbESTADOconsulta.addItem("Concluída");
        this.jcbESTADOconsulta.addItem("Descartada");
        this.jcbESTADOconsulta.addItem("Em andamento");
        
        this.jcbTIPOconsulta.addItem("S/A");
        this.jcbTIPOconsulta.addItem("MELHORIA");
        this.jcbTIPOconsulta.addItem("DEFEITO");
        
        this.jcbRELATORconsulta.addItem("S/A");
        this.jcbEXECUTORconsulta.addItem("S/A");
        
        //this.jcbTAREFASprojeto.addItem("Nenhuma");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNOME = new javax.swing.JTextField();
        txtCARGO = new javax.swing.JTextField();
        txtSETOR = new javax.swing.JTextField();
        criaPERFIL = new javax.swing.JButton();
        jcbTIPOPerfil = new javax.swing.JComboBox<>();
        mostraPERFIS = new javax.swing.JButton();
        limpaTabelaPERFIS = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaPERFIL = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jcbEXECUTOR = new javax.swing.JComboBox<>();
        jcbTIPO = new javax.swing.JComboBox<>();
        txtNOMEtarefa = new javax.swing.JTextField();
        txtDESCRICAO = new javax.swing.JTextField();
        cadastraTAREFA = new javax.swing.JButton();
        jcbRELATOR = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaTAREFAS = new javax.swing.JTable();
        mostraNomeTAREFAS = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jcbTarefaparaINICIAR = new javax.swing.JComboBox<>();
        txtINICIOtarefa = new javax.swing.JTextField();
        txtPrazoTAREFA = new javax.swing.JTextField();
        iniciaTAREFA = new javax.swing.JButton();
        jcbMostraEstado = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jcbTarefaparaCONCLUIR = new javax.swing.JComboBox<>();
        concluiTAREFA = new javax.swing.JButton();
        txtTarefaSOLUCAO = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        mostraTAREFASconcluidas = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jcbTarefaparaDESCARTAR = new javax.swing.JComboBox<>();
        descartarTAREFA = new javax.swing.JButton();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jcbUSUARIOiniciar = new javax.swing.JComboBox<>();
        jcbUSUARIOconcluir = new javax.swing.JComboBox<>();
        jcbUSUARIOdescatar = new javax.swing.JComboBox<>();
        jLabel34 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        projetoNOME = new javax.swing.JTextField();
        criaPROJETO = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jcbTAREFASprojeto = new javax.swing.JComboBox<>();
        jcbPROJETOSadicionarTAREFAS = new javax.swing.JComboBox<>();
        ADICIONARtarefaPROJETO = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jcbPROJETOSiniciar = new javax.swing.JComboBox<>();
        iniciaPROJETO = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        txtINICIOprojeto = new javax.swing.JTextField();
        txtPRAZOprojeto = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jcbPROJETOSconcluir = new javax.swing.JComboBox<>();
        concluiPROJETO = new javax.swing.JButton();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        alteraFASE = new javax.swing.JButton();
        jcbProjetofase = new javax.swing.JComboBox<>();
        jcbFASE = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jcbPROJETOconsulta = new javax.swing.JComboBox<>();
        jcbFASEconsulta = new javax.swing.JComboBox<>();
        jcbTIPOconsulta = new javax.swing.JComboBox<>();
        jcbESTADOconsulta = new javax.swing.JComboBox<>();
        jcbRELATORconsulta = new javax.swing.JComboBox<>();
        jcbEXECUTORconsulta = new javax.swing.JComboBox<>();
        jLabel44 = new javax.swing.JLabel();
        jcbUSUARIOSconsulta = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SISTEMA DE CONTROLE DE TAREFAS");

        jPanel1.setPreferredSize(new java.awt.Dimension(160, 250));

        jLabel2.setText("Nome:");

        jLabel3.setText("Perfil:");

        jLabel4.setText("Cargo:");

        jLabel5.setText("Setor:");

        txtNOME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNOMEActionPerformed(evt);
            }
        });

        criaPERFIL.setText("ADICIONAR");
        criaPERFIL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                criaPERFILActionPerformed(evt);
            }
        });

        mostraPERFIS.setText("MOSTRAR");
        mostraPERFIS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostraPERFISActionPerformed(evt);
            }
        });

        limpaTabelaPERFIS.setText("Limpar");
        limpaTabelaPERFIS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpaTabelaPERFISActionPerformed(evt);
            }
        });

        jLabel1.setText("CAMPO PERFIL");

        tabelaPERFIL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Perfil", "Tipo", "Cargo", "Setor"
            }
        ));
        jScrollPane1.setViewportView(tabelaPERFIL);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSETOR))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNOME)
                                    .addComponent(txtCARGO)
                                    .addComponent(jcbTIPOPerfil, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(72, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(criaPERFIL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(mostraPERFIS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(limpaTabelaPERFIS, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(60, 60, 60)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(216, 216, 216))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtNOME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jcbTIPOPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtCARGO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtSETOR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(criaPERFIL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mostraPERFIS)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(limpaTabelaPERFIS)))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jLabel7.setText("RELATOR:");

        jLabel8.setText("EXECUTOR:");

        jLabel9.setText("NOME:");

        jLabel10.setText("TIPO:");

        jLabel11.setText("DESCRIÇÃO:");

        jcbTIPO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbTIPOActionPerformed(evt);
            }
        });

        txtNOMEtarefa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNOMEtarefaActionPerformed(evt);
            }
        });

        cadastraTAREFA.setText("CADASTRAR");
        cadastraTAREFA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastraTAREFAActionPerformed(evt);
            }
        });

        tabelaTAREFAS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Testes"
            }
        ));
        jScrollPane2.setViewportView(tabelaTAREFAS);

        mostraNomeTAREFAS.setText("MOSTRAR");
        mostraNomeTAREFAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostraNomeTAREFASActionPerformed(evt);
            }
        });

        jLabel12.setText("TAREFA:");

        jLabel14.setText("INÍCIO:");

        jLabel15.setText("PRAZO:");

        iniciaTAREFA.setText("INICIAR");
        iniciaTAREFA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciaTAREFAActionPerformed(evt);
            }
        });

        jLabel13.setText("TAREFA:");

        jcbTarefaparaCONCLUIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbTarefaparaCONCLUIRActionPerformed(evt);
            }
        });

        concluiTAREFA.setText("CONCLUIR");
        concluiTAREFA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                concluiTAREFAActionPerformed(evt);
            }
        });

        txtTarefaSOLUCAO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTarefaSOLUCAOActionPerformed(evt);
            }
        });

        jLabel16.setText("SOLUÇÃO:");

        mostraTAREFASconcluidas.setText("MOSTRAR");
        mostraTAREFASconcluidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostraTAREFASconcluidasActionPerformed(evt);
            }
        });

        jLabel17.setText("TAREFA:");

        jLabel18.setText("DESCARTAR");

        jLabel19.setText("CONCLUIR");

        jLabel20.setText("INICIAR");

        jLabel21.setText("CADASTRAR");

        jLabel6.setText("CAMPO TAREFA");

        descartarTAREFA.setText("DESCARTAR");
        descartarTAREFA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descartarTAREFAActionPerformed(evt);
            }
        });

        jLabel32.setText("Usuário:");

        jLabel33.setText("Usuário:");

        jLabel34.setText("Usuário:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(33, 33, 33)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(cadastraTAREFA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(mostraNomeTAREFAS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel8)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jcbEXECUTOR, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jcbRELATOR, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtDESCRICAO)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jcbTIPO, 0, 99, Short.MAX_VALUE)
                                            .addComponent(txtNOMEtarefa))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel11)
                                .addGap(61, 61, 61)))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtINICIOtarefa, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtPrazoTAREFA, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel32)
                                                .addComponent(jLabel12))
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                    .addGap(6, 6, 6)
                                                    .addComponent(iniciaTAREFA, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(jcbTarefaparaINICIAR, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jcbUSUARIOiniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel20)
                                            .addComponent(jLabel6))
                                        .addGap(69, 69, 69)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(99, 99, 99)
                                        .addComponent(jLabel19))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(33, 33, 33)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel33)
                                                .addGap(18, 18, 18)
                                                .addComponent(jcbUSUARIOconcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel13)
                                                    .addComponent(jLabel16))
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                            .addComponent(txtTarefaSOLUCAO)
                                                            .addComponent(jcbTarefaparaCONCLUIR, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                                        .addGap(6, 6, 6)
                                                        .addComponent(mostraTAREFASconcluidas, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(concluiTAREFA, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                                .addGap(120, 120, 120))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jcbMostraEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(descartarTAREFA)
                                .addGap(280, 280, 280))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(196, 196, 196)
                                .addComponent(jLabel18))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(151, 151, 151)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel34))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jcbUSUARIOdescatar, 0, 120, Short.MAX_VALUE)
                                    .addComponent(jcbTarefaparaDESCARTAR, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel33)
                            .addComponent(jcbUSUARIOconcluir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jcbTarefaparaCONCLUIR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTarefaSOLUCAO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(concluiTAREFA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mostraTAREFASconcluidas)
                        .addGap(13, 13, 13))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel21))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel20)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(jcbRELATOR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(jcbEXECUTOR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(txtNOMEtarefa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jcbTIPO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel32)
                                    .addComponent(jcbUSUARIOiniciar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jcbTarefaparaINICIAR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtINICIOtarefa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel15)
                                    .addComponent(txtPrazoTAREFA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(iniciaTAREFA)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)))
                .addComponent(jLabel18)
                .addGap(97, 97, 97))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtDESCRICAO, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cadastraTAREFA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mostraNomeTAREFAS)
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jcbUSUARIOdescatar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel34))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel17)
                                    .addComponent(jcbTarefaparaDESCARTAR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(descartarTAREFA)
                                    .addComponent(jcbMostraEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );

        jLabel22.setText("CAMPO PROJETO");

        jLabel23.setText("NOVO PROJETO");

        jLabel24.setText("Nome:");

        criaPROJETO.setText("CRIAR");
        criaPROJETO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                criaPROJETOActionPerformed(evt);
            }
        });

        jLabel25.setText("ADICIONAR TAREFAS");

        jLabel26.setText("Tarefa:");

        jLabel27.setText("Projeto:");

        jcbTAREFASprojeto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbTAREFASprojetoActionPerformed(evt);
            }
        });

        ADICIONARtarefaPROJETO.setText("ADICIONAR");
        ADICIONARtarefaPROJETO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADICIONARtarefaPROJETOActionPerformed(evt);
            }
        });

        jLabel28.setText("INICIAR PROJETO");

        jLabel29.setText("Projeto:");

        iniciaPROJETO.setText("INICIAR");
        iniciaPROJETO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciaPROJETOActionPerformed(evt);
            }
        });

        jLabel30.setText("Início:");

        jLabel31.setText("Prazo:");

        jLabel35.setText("CONCLUIR PROJETO");

        jLabel36.setText("Projeto:");

        jcbPROJETOSconcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbPROJETOSconcluirActionPerformed(evt);
            }
        });

        concluiPROJETO.setText("CONCLUIR");
        concluiPROJETO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                concluiPROJETOActionPerformed(evt);
            }
        });

        jLabel45.setText("ALTERA FASE");

        jLabel46.setText("Fase:");

        jLabel47.setText("Projeto:");

        alteraFASE.setText("ALTERAR");
        alteraFASE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alteraFASEActionPerformed(evt);
            }
        });

        jcbProjetofase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbProjetofaseActionPerformed(evt);
            }
        });

        jcbFASE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbFASEActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jLabel23))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(projetoNOME, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel27)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jcbPROJETOSadicionarTAREFAS, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel25))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel26)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jcbTAREFASprojeto, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(criaPROJETO)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ADICIONARtarefaPROJETO)
                        .addGap(42, 42, 42)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel28))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel30)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtINICIOprojeto))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel29)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jcbPROJETOSiniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel31)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtPRAZOprojeto, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(iniciaPROJETO)
                        .addGap(36, 36, 36)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel47)
                            .addComponent(jLabel46))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcbProjetofase, 0, 125, Short.MAX_VALUE)
                            .addComponent(jcbFASE, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel36)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(concluiPROJETO)
                            .addComponent(jcbPROJETOSconcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(alteraFASE)
                            .addComponent(jLabel45))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel35)
                        .addGap(28, 28, 28))))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(278, 278, 278)
                .addComponent(jLabel22)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel22)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24)
                            .addComponent(projetoNOME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel26)
                            .addComponent(jcbTAREFASprojeto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jcbPROJETOSadicionarTAREFAS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel27)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel28)
                            .addComponent(jLabel35)
                            .addComponent(jLabel45))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel29)
                                    .addComponent(jcbPROJETOSiniciar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel30)
                                    .addComponent(txtINICIOprojeto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel31)
                                    .addComponent(txtPRAZOprojeto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(10, 10, 10)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(iniciaPROJETO)
                                    .addComponent(ADICIONARtarefaPROJETO)
                                    .addComponent(criaPROJETO)
                                    .addComponent(alteraFASE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel36)
                                            .addComponent(jcbPROJETOSconcluir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jcbProjetofase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jcbFASE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel46)))
                                    .addComponent(jLabel47, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(45, 45, 45)
                                .addComponent(concluiPROJETO)))))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel37.setText("CAMPO DE CONSULTAS");

        jLabel38.setText("Por Projeto:");

        jLabel39.setText("Por Fase de Projeto:");

        jLabel40.setText("Por Tipo de Tarefa:");

        jLabel41.setText("Por Estado da Tarefa:");

        jLabel42.setText("Por Relator:");

        jLabel43.setText("Por Executor:");

        jcbPROJETOconsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbPROJETOconsultaActionPerformed(evt);
            }
        });

        jcbFASEconsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbFASEconsultaActionPerformed(evt);
            }
        });

        jcbTIPOconsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbTIPOconsultaActionPerformed(evt);
            }
        });

        jLabel44.setText("Usuário:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel37)
                .addGap(282, 282, 282))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel44)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jcbUSUARIOSconsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel38)
                        .addGap(70, 70, 70))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel42)
                            .addComponent(jLabel41, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel40)
                            .addComponent(jLabel39, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jcbRELATORconsulta, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jcbFASEconsulta, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jcbPROJETOconsulta, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jcbTIPOconsulta, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jcbESTADOconsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbEXECUTORconsulta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(115, 115, 115))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel37)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38)
                    .addComponent(jcbPROJETOconsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbFASEconsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel39))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbTIPOconsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel40)
                    .addComponent(jLabel44)
                    .addComponent(jcbUSUARIOSconsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbESTADOconsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel41))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbRELATORconsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel42))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel43)
                    .addComponent(jcbEXECUTORconsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(119, 119, 119)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 736, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 9, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void criaPERFILActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criaPERFILActionPerformed
        
        Perfil perfil = new Perfil();
        
        perfil.Perfil(txtNOME.getText(), txtCARGO.getText(), this.jcbTIPOPerfil.getSelectedItem().toString(), txtSETOR.getText());
        
        //Cria uma lista de perfis gerados no sistema
        perfis.add(perfil);
        
        //Crias as DASHBoard do RELATOR e do EXECUTOR para criação da tarefa        
        if("Administrador".equals(perfil.getTipoPerfil()))
        {
               this.jcbRELATOR.addItem(perfil.getNomeUsuario());
        }
        
        if("Usuário".equals(perfil.getTipoPerfil()))
        {
               this.jcbEXECUTOR.addItem(perfil.getNomeUsuario());
               this.jcbUSUARIOiniciar.addItem(perfil.getNomeUsuario());
               this.jcbUSUARIOconcluir.addItem(perfil.getNomeUsuario());
               this.jcbUSUARIOdescatar.addItem(perfil.getNomeUsuario());
        }
        
        this.jcbUSUARIOSconsulta.addItem(perfil.getNomeUsuario());
        
        DefaultTableModel dtmPERFIL = (DefaultTableModel) tabelaPERFIL.getModel();
        
        //for(int i=0;i<perfis.size();i++){
            Object [] dados  = {perfis.get(ii).getNomeUsuario(), perfis.get(ii).getTipoPerfil(), perfis.get(ii).getCargo(),perfis.get(ii).getSetorTrabalho()};
        
            dtmPERFIL.addRow(dados);
        //}
        ii++;
    }//GEN-LAST:event_criaPERFILActionPerformed
    
    private void txtNOMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNOMEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNOMEActionPerformed

    private void mostraPERFISActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostraPERFISActionPerformed
        
        /*MostrarPerfil tabelaPerfil = new MostrarPerfil(this,true);
        
        tabelaPerfil.setVisible(true);
        
        tabelaPerfil.recebeArray(perfis);*/
        DefaultTableModel dtmPERFIL = (DefaultTableModel) tabelaPERFIL.getModel();
        
        for(int i=0;i<perfis.size();i++){
            Object [] dados  = {perfis.get(i).getNomeUsuario(), perfis.get(i).getTipoPerfil(), perfis.get(i).getCargo(),perfis.get(i).getSetorTrabalho()};
        
            dtmPERFIL.addRow(dados);
        }
    }//GEN-LAST:event_mostraPERFISActionPerformed

    private void limpaTabelaPERFISActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpaTabelaPERFISActionPerformed
        DefaultTableModel dtmPERFIL = (DefaultTableModel) tabelaPERFIL.getModel();
        
        for(int i=0;i<perfis.size();i++){
            dtmPERFIL.removeRow(0);
        }
    }//GEN-LAST:event_limpaTabelaPERFISActionPerformed

    private void mostraTAREFASconcluidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostraTAREFASconcluidasActionPerformed

        for(int i=0; i<tarefas.size();i++){
            if(tarefas.get(i).isConcluida()){
                JOptionPane.showMessageDialog(null,"Tarefa: "+tarefas.get(i).getTarefaNome());
            }
        }
    }//GEN-LAST:event_mostraTAREFASconcluidasActionPerformed

    private void txtTarefaSOLUCAOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTarefaSOLUCAOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTarefaSOLUCAOActionPerformed

    private void concluiTAREFAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_concluiTAREFAActionPerformed
        int count4 = 0;

        String nome3 = null;
        String nome4 = null;

        for(int i=0;i<tarefas.size();i++){
            if(tarefas.get(i).getTarefaNome()==this.jcbTarefaparaCONCLUIR.getSelectedItem())
            {
                if(tarefas.get(i).getTarefaExecutor().getNomeUsuario()==this.jcbUSUARIOconcluir.getSelectedItem())
                {
                    tarefas.get(i).concluirTarefa(txtTarefaSOLUCAO.getText(), true); //selecionar dados no txt de inicio e converter para date
                
                    //Excluir
                    nome3=tarefas.get(i).getTarefaRelator().getNomeUsuario();
                    nome4=tarefas.get(i).getTarefaExecutor().getNomeUsuario();

                    count4=i;
                }
                
                
            }
        }

        //Excluir
        for(int j=0;j<perfis.size();j++){
            if(nome3==perfis.get(j).getNomeUsuario()){
                perfis.get(j).adicionarTarefa(tarefas.get(count4));
            }
            if(nome4==perfis.get(j).getNomeUsuario()){
                perfis.get(j).adicionarTarefa(tarefas.get(count4));
            }

            //Incluir comandos para Projetos
        }

    }//GEN-LAST:event_concluiTAREFAActionPerformed

    private void jcbTarefaparaCONCLUIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbTarefaparaCONCLUIRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbTarefaparaCONCLUIRActionPerformed

    private void iniciaTAREFAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciaTAREFAActionPerformed

        //Tarefa tarefa;
        
        int prazo = Integer.parseInt(txtPrazoTAREFA.getText());

        int count3 = 0;

        String nome1 = null;
        String nome2 = null;

        for(int i=0;i<tarefas.size();i++)
        {
            if(tarefas.get(i).getTarefaNome()==this.jcbTarefaparaINICIAR.getSelectedItem())
            {
                if(tarefas.get(i).getTarefaExecutor().getNomeUsuario()==this.jcbUSUARIOiniciar.getSelectedItem())
                {
                    tarefas.get(i).iniciarTarefa(LocalDate.now(), prazo);
                        
                    //tarefa.iniciarTarefa(LocalDate.now(), prazo); //selecionar dados no txt de inicio e converter para date

                    //Excluir ou não usar
                    nome1=tarefas.get(i).getTarefaRelator().getNomeUsuario();//Perfil(i).getNomeUsuario();
                    nome2=tarefas.get(i).getTarefaExecutor().getNomeUsuario();

                   // tarefas.set(i, tarefa);

                    count3=i;
                    
                    //Cria a DASHboard de tarefas a serem CONCLUÍDAS
                    this.jcbTarefaparaCONCLUIR.addItem(tarefas.get(i).getTarefaNome());

                    //Cria a DASHboard de tarefas a serem DESCARTAR
                    this.jcbTarefaparaDESCARTAR.addItem(tarefas.get(i).getTarefaNome());
                } else {
                    JOptionPane.showMessageDialog(null,"Este não é o executor desta tarefa!");
                }
            }
        }
        
        /*Excluir
        for(int j=0;j<perfis.size();j++){
            if(nome1==perfis.get(j).getNomeUsuario()){
                perfis.get(j).adicionarTarefa(tarefas.get(count3));
            }
            if(nome2==perfis.get(j).getNomeUsuario()){
                perfis.get(j).adicionarTarefa(tarefas.get(count3));
            }
        }*/
        
        

        //Apenas para teste... Provável de apagar
        /*for (int j=0;j<tarefas.size();j++){
            if(tarefas.get(j).tarefaEstado()){
                jcbMostraEstado.addItem(tarefas.get(j).toString());
                JOptionPane.showMessageDialog(null, "Valor: "+tarefas.get(j).toString() );
            }
        }*/

        /*if(txtPrazoTAREFA.getText()==null||txtINICIOtarefa.getText()==null){
            JOptionPane.showMessageDialog(null, "Informe todos os parâmetros");
        }*/
    }//GEN-LAST:event_iniciaTAREFAActionPerformed

    private void mostraNomeTAREFASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostraNomeTAREFASActionPerformed
        DefaultTableModel dtmTAREFA = (DefaultTableModel) tabelaTAREFAS.getModel();

        for(int i=0;i<tarefas.size();i++){
            Object [] dados  = {tarefas.get(i).getTarefaNome()};//, perfis.get(i).getTipoPerfil(), perfis.get(i).getCargo(),perfis.get(i).getSetorTrabalho()};

        dtmTAREFA.addRow(dados);
        }
    }//GEN-LAST:event_mostraNomeTAREFASActionPerformed

    private void cadastraTAREFAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastraTAREFAActionPerformed
        Perfil p1 = new Perfil();
        Perfil p2 = new Perfil();

        Tarefa tarefa = new Tarefa();

        //int count1=0, count2=0;

        for(int i=0;i<perfis.size();i++){
            if(perfis.get(i).getNomeUsuario()==this.jcbRELATOR.getSelectedItem()){
                p1 = perfis.get(i);
                //count1 = i;
            }
            if(perfis.get(i).getNomeUsuario()==this.jcbEXECUTOR.getSelectedItem()){
                p2 = perfis.get(i);
                //count2 = i;
            }
        }

        //Cria o objeto TAREFA
        tarefa.cadastrarTarefa(p1, p2, txtNOMEtarefa.getText(),jcbTIPO.getSelectedItem().toString());

        //Vincula a tarefa criada ao RELATOR e ao EXECUTOR
        /*perfis.get(count1).adicionarTarefa(tarefa);
        perfis.get(count2).adicionarTarefa(tarefa);*/

        //Cria a lista de tarefas do sistema
        tarefas.add(tarefa);

        //Cria a DASHboard de tarefas a serem INICIADAS
        this.jcbTarefaparaINICIAR.addItem(tarefa.getTarefaNome());
        
        //Cria a DASHBOARD de tarefas a serem ADICIONADAS a Projetos
        this.jcbTAREFASprojeto.addItem(tarefa.getTarefaNome());

    }//GEN-LAST:event_cadastraTAREFAActionPerformed

    private void txtNOMEtarefaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNOMEtarefaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNOMEtarefaActionPerformed

    private void descartarTAREFAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descartarTAREFAActionPerformed
        int count5 = 0;

        String nome5 = null;
        String nome6 = null;

        for(int i=0;i<tarefas.size();i++){
            if(tarefas.get(i).getTarefaNome()==this.jcbTarefaparaDESCARTAR.getSelectedItem())
            {
                if(tarefas.get(i).getTarefaExecutor().getNomeUsuario()==this.jcbUSUARIOdescatar.getSelectedItem())
                {
                    tarefas.get(i).descartarTarefa(true); //selecionar dados no txt de inicio e converter para date
                    
                    //Exlcuir
                    nome5=tarefas.get(i).getTarefaRelator().getNomeUsuario();//Perfil(i).getNomeUsuario();
                    nome6=tarefas.get(i).getTarefaExecutor().getNomeUsuario();

                    count5=i;
                    //Excluir (acima)
                }
            }
        }

        for(int j=0;j<perfis.size();j++){
            if(nome5==perfis.get(j).getNomeUsuario()){
                perfis.get(j).adicionarTarefa(tarefas.get(count5));
            }
            if(nome6==perfis.get(j).getNomeUsuario()){
                perfis.get(j).adicionarTarefa(tarefas.get(count5));
            }
        }
    }//GEN-LAST:event_descartarTAREFAActionPerformed

    private void criaPROJETOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criaPROJETOActionPerformed
        //this.jcbPROJETOSconsulta.enable();
        
        Projeto projeto = new Projeto();
        
        projeto.criarProjeto(projetoNOME.getText());
        
        this.jcbPROJETOSadicionarTAREFAS.addItem(projetoNOME.getText());
        
        this.jcbPROJETOSiniciar.addItem(projetoNOME.getText());
        
        this.jcbPROJETOSconcluir.addItem(projetoNOME.getText());
        
        this.jcbPROJETOconsulta.addItem(projetoNOME.getText());
        
        projetos.add(projeto);
        
    }//GEN-LAST:event_criaPROJETOActionPerformed

    private void jcbTAREFASprojetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbTAREFASprojetoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbTAREFASprojetoActionPerformed

    private void ADICIONARtarefaPROJETOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADICIONARtarefaPROJETOActionPerformed
        
        //LocalDate hoje = LocalDate.now();
        
        //int prazo = Integer.parseInt(txtPRAZOprojeto.getText());
        
        for(int i=0;i<projetos.size();i++)
        {
            if(jcbPROJETOSadicionarTAREFAS.getSelectedItem()==projetos.get(i).getProjNome())
            {
                //projetos.get(i).iniciarProjeto(LocalDate.now(), prazo);
                for(int j=0;j<tarefas.size();j++)
                {
                    if(this.jcbTAREFASprojeto.getSelectedItem()==tarefas.get(j).getTarefaNome())
                    {
                        //Vincula o PROJETO criado à TAREFA
                        tarefas.get(j).setProjetoVinculadoNome(projetos.get(i));

                        /*Excluir
                        //Adiciona TAREFA e os PERFIS vinculados à mesma em um Objeto PROJETO
                        projetos.get(i).adicionarTarefa(tarefas.get(j));
                        projetos.get(i).adicionarPerfil(tarefas.get(j).getPerfisTarefa(0));
                        projetos.get(i).adicionarPerfil(tarefas.get(j).getPerfisTarefa(1));
                        
                        for(int k=0;k<perfis.size();k++)
                        {
                            //Atualiza o perfil do RELATOR
                            if(tarefas.get(j).getPerfisTarefa(0).getNomeUsuario()==perfis.get(k).getNomeUsuario())
                            {
                                for(int m=0;m<perfis.get(k).quantidadeTarefas();m++)
                                {
                                    if(perfis.get(k).getTarefasPerfil(m).getTarefaNome()==this.jcbTAREFASprojeto.getSelectedItem())
                                    {
                                        perfis.get(k).atualizaTarefa(m, tarefas.get(j));
                                    }
                                }
                            }
                            
                            //Atualiza o perfil do EXECUTOR
                            if(tarefas.get(j).getPerfisTarefa(1).getNomeUsuario()==perfis.get(k).getNomeUsuario())
                            {
                                for(int m=0;m<perfis.get(k).quantidadeTarefas();m++)
                                {
                                    if(perfis.get(k).getTarefasPerfil(m).getTarefaNome()==this.jcbTAREFASprojeto.getSelectedItem())
                                    {
                                        perfis.get(k).atualizaTarefa(m, tarefas.get(j));
                                    }
                                }
                            }
                        }*/
                    }
                }
            }
        }
    }//GEN-LAST:event_ADICIONARtarefaPROJETOActionPerformed

    private void iniciaPROJETOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciaPROJETOActionPerformed
        
        LocalDate hoje = LocalDate.now();
        
        int prazo = Integer.parseInt(txtPRAZOprojeto.getText());
        
        for(int i=0;i<projetos.size();i++)
        {
            if(projetos.get(i).getProjNome()==this.jcbPROJETOSadicionarTAREFAS.getSelectedItem())
            {
                projetos.get(i).iniciarProjeto(LocalDate.now(), prazo);
                
                for (int k=0;k<tarefas.size();k++)
                {
                    if(tarefas.get(k).getProjetoVinculadoNome().getProjNome().equals(projetos.get(i).getProjNome()))
                            {
                                //Atualiza a tarefa  com projeto iniciado
                                tarefas.get(k).setProjetoVinculadoNome(projetos.get(i));
                            }
                }
            }
        }
                            
            /* EXCLUIR
            for (int j=0;j<perfis.size();j++)
            {
                for(int m=0;m<perfis.get(j).quantidadeProjetos();m++)
                {
                    //Atualiza o PERFIL com o projeto iniciado
                    if(projetos.get(i).getProjNome()==perfis.get(j).getProjetosPerfil(m).getProjNome())
                    {
                        perfis.get(j).atualizaProjeto(m, projetos.get(i));
                        
                        for (int k=0;k<tarefas.size();k++)
                        {
                            if(tarefas.get(k).getProjetoVinculadoNome().getProjNome()==projetos.get(i).getProjNome())
                            {
                                //Atualiza a tarefa  com projeto iniciado
                                tarefas.get(k).setProjetoVinculadoNome(projetos.get(i));

                                for(int u=0;u<tarefas.get(k).quantidadePerfis();u++)
                                {
                                    for(int t=0;t<perfis.size();t++)
                                    {
                                        //Atualiza tarefa com o perfil
                                        if(tarefas.get(k).getPerfisTarefa(u).getNomeUsuario()==perfis.get(t).getNomeUsuario())
                                        {
                                            tarefas.get(k).atualizaPerfil(u, perfis.get(t));
                                        }
                                    }

                                }
                            }
                        }
                    }
                }
            }*/
    }//GEN-LAST:event_iniciaPROJETOActionPerformed

    private void concluiPROJETOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_concluiPROJETOActionPerformed
        
        for(int i=0;i<projetos.size();i++)
        {
            if(this.jcbPROJETOSconcluir.getSelectedItem()==projetos.get(i).getProjNome())
            {
                for(int j=0;j<tarefas.size();j++)
                {
                    if(tarefas.get(j).getProjetoVinculadoNome().getProjNome()==this.jcbPROJETOSconcluir.getSelectedItem())
                    {
                        projetos.get(i).concluirProjeto(true);
                        
                        tarefas.get(j).setProjetoVinculadoNome(projetos.get(i));
                    }
                }
            }
        }
    }//GEN-LAST:event_concluiPROJETOActionPerformed

    private void jcbTIPOconsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbTIPOconsultaActionPerformed
        Consulta cons = new Consulta();
        
        cons.porTipoDeTAREFA(String.valueOf(this.jcbTIPOconsulta.getSelectedItem()), tarefas);
    }//GEN-LAST:event_jcbTIPOconsultaActionPerformed

    private void jcbPROJETOconsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbPROJETOconsultaActionPerformed
        Consulta c = new Consulta();
        
        c.porPROJETO(String.valueOf(this.jcbPROJETOconsulta.getSelectedItem()).toUpperCase(), tarefas);
    }//GEN-LAST:event_jcbPROJETOconsultaActionPerformed

    private void jcbFASEconsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbFASEconsultaActionPerformed
        Consulta cons = new Consulta();
        
        cons.porFASE(String.valueOf(this.jcbFASEconsulta.getSelectedItem()), tarefas);
    }//GEN-LAST:event_jcbFASEconsultaActionPerformed

    private void jcbTIPOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbTIPOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbTIPOActionPerformed

    private void jcbPROJETOSconcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbPROJETOSconcluirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbPROJETOSconcluirActionPerformed

    private void jcbProjetofaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbProjetofaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbProjetofaseActionPerformed

    private void jcbFASEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbFASEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbFASEActionPerformed

    private void alteraFASEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alteraFASEActionPerformed
        for(int i=0;i<projetos.size();i++)
        {
            if(projetos.get(i).getProjNome()==this.jcbProjetofase.getSelectedItem())
            {
                projetos.get(i).setProjFase(String.valueOf(this.jcbProjetofase.getSelectedItem()));
                
                for(int j=0;j<tarefas.size();j++)
                {
                    if(tarefas.get(j).getProjetoVinculadoNome().getProjNome()==projetos.get(i).getProjNome())
                    {
                        tarefas.get(j).setProjetoVinculadoNome(projetos.get(i));
                    }
                }
            }
        }
    }//GEN-LAST:event_alteraFASEActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sistema().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ADICIONARtarefaPROJETO;
    private javax.swing.JButton alteraFASE;
    private javax.swing.JButton cadastraTAREFA;
    private javax.swing.JButton concluiPROJETO;
    private javax.swing.JButton concluiTAREFA;
    private javax.swing.JButton criaPERFIL;
    private javax.swing.JButton criaPROJETO;
    private javax.swing.JButton descartarTAREFA;
    private javax.swing.JButton iniciaPROJETO;
    private javax.swing.JButton iniciaTAREFA;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> jcbESTADOconsulta;
    private javax.swing.JComboBox<String> jcbEXECUTOR;
    private javax.swing.JComboBox<String> jcbEXECUTORconsulta;
    private javax.swing.JComboBox<String> jcbFASE;
    private javax.swing.JComboBox<String> jcbFASEconsulta;
    private javax.swing.JComboBox<String> jcbMostraEstado;
    private javax.swing.JComboBox<String> jcbPROJETOSadicionarTAREFAS;
    private javax.swing.JComboBox<String> jcbPROJETOSconcluir;
    private javax.swing.JComboBox<String> jcbPROJETOSiniciar;
    private javax.swing.JComboBox<String> jcbPROJETOconsulta;
    private javax.swing.JComboBox<String> jcbProjetofase;
    private javax.swing.JComboBox<String> jcbRELATOR;
    private javax.swing.JComboBox<String> jcbRELATORconsulta;
    private javax.swing.JComboBox<String> jcbTAREFASprojeto;
    private javax.swing.JComboBox<String> jcbTIPO;
    private javax.swing.JComboBox<String> jcbTIPOPerfil;
    private javax.swing.JComboBox<String> jcbTIPOconsulta;
    private javax.swing.JComboBox<String> jcbTarefaparaCONCLUIR;
    private javax.swing.JComboBox<String> jcbTarefaparaDESCARTAR;
    private javax.swing.JComboBox<String> jcbTarefaparaINICIAR;
    private javax.swing.JComboBox<String> jcbUSUARIOSconsulta;
    private javax.swing.JComboBox<String> jcbUSUARIOconcluir;
    private javax.swing.JComboBox<String> jcbUSUARIOdescatar;
    private javax.swing.JComboBox<String> jcbUSUARIOiniciar;
    private javax.swing.JButton limpaTabelaPERFIS;
    private javax.swing.JButton mostraNomeTAREFAS;
    private javax.swing.JButton mostraPERFIS;
    private javax.swing.JButton mostraTAREFASconcluidas;
    private javax.swing.JTextField projetoNOME;
    private javax.swing.JTable tabelaPERFIL;
    private javax.swing.JTable tabelaTAREFAS;
    private javax.swing.JTextField txtCARGO;
    private javax.swing.JTextField txtDESCRICAO;
    private javax.swing.JTextField txtINICIOprojeto;
    private javax.swing.JTextField txtINICIOtarefa;
    private javax.swing.JTextField txtNOME;
    private javax.swing.JTextField txtNOMEtarefa;
    private javax.swing.JTextField txtPRAZOprojeto;
    private javax.swing.JTextField txtPrazoTAREFA;
    private javax.swing.JTextField txtSETOR;
    private javax.swing.JTextField txtTarefaSOLUCAO;
    // End of variables declaration//GEN-END:variables
}
